apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 
  namespace: argocd
spec:
  destination:
    namespace: actions-runner-system
    server: https://kubernetes.default.svc
  project: vcluster-gitops
  source:
    chart: actions-runner-controller
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    targetRevision: 0.16.1
    helm:
      releaseName: actions-runner-controller
      values: |-
        authSecret:
          github_token: Z2hwX0xTZ2NudTJ2NzU0VWtJZElNRjQyWTBjZExQY29zRjBrQ3VTbwo=
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
