{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "controller-manager",
    "namespace": "actions-runner-system",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "controller-manager",
        "namespace": "actions-runner-system",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "github_token": "AgCW0ZwXrXrIyZat4n+GIZrVHLyWOg5FN1smqKG7JewxRNcIXJ+jy/7FbvTNbnlcmA2EDX43yk2nGXy9e68yVRuJPkm4mf/v8OU9TU7qOK2L5T+sJ5d9SNABoCT2Ng3caGhEQw93z6RqT7CcmByVRgVetp+w5XpqRrxkEu8N0HaR4sE4B/wTiyEb9I7B98X3z6YTuXS+6lSHiH17rABKvk7MW8raVM+oPpBwEC8kMlAkBDbnmBfAYRqX7ywVn5HbtLi8tUgX8nNS5ueUpjJJbXiAYGiRf7HXUMLeLiCTdXsqcCAOWt6k8Z10+06/Pfw+9p8iYt/OR5Hbx50Ab0DqpZyO7Kd0zaTTRfqrR2MqftQliAL+A9pP/t7Ec24DeLfRDvdNqIULNCCBk7BzGZaTkjbomm62sCiz8iFZ5Ik7lBrz0SrClqxdzNjXMsss0WVCu5gUmR4ZAeIFZImCGP3xEd/gRoXRJg3MVYBNSYZzuJ5TcfnUZtB8PMBR8KnUpDgBjOTRgWsHE6Fe/XUyUSBpLpfsep2bUNTiRleLJkOvf5eJzVScuJjmnlL242CCElqQ+1CYp/AkmCMb4pf2W3vHa/ldsjTiGiuRZrY5OUGEJa8xDWXt39a5uZS5BynaQQAz1BfNXR8q907+ONr4JTg6s8y06YCdK3RA9Mf7Bj+A9G/RjMdQxzVlABKMom3zMpYuNwLyo/ASl7ERisVa35r9YcGxAbeP1s87BMrsD5hZPBTx1cFlFAth5rM6"
    }
  }
}
