apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vcluster-k3s-121
  namespace: k3s
spec:
  hosts:
  - "*"
  gateways:
  - istio-ingress/vcluster
  tls:
  - match:
    - port: 443
      sniHosts:
      - "vcluster-k3s-121"
    route:
    - destination:
        host: vcluster-k3s-121
        port:
          number: 443
