apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-vs
  namespace: tests
spec:
  hosts:
  - "*"
  gateways:
  - istio-ingress/vcluster
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: test-x-apps-x-vcluster
        port:
          number: 80

