apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-k8s-121
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: k8s
    server: https://kubernetes.default.svc
  project: vcluster
  source:
    chart: vcluster-k8s
    helm:
      releaseName: vcluster-k8s-121
      parameters:
      - name: service.type
        value: ClusterIP
      - name: serviceCIDR
        value: "10.43.0.0/12"
      - name: syncer.extraArgs
        value: '{--tls-san=vcluster-k8s-121.172.18.0.3.nip.io,vcluster-k8s-121.k8s.svc.cluster.local}'
      - name: sync.services.enabled
        value: 'true'
      - name: sync.configmaps.enabled
        value: 'true'
      - name: sync.secrets.enabled
        value: 'true'
      - name: sync.endpoints.enabled
        value: 'true'
      - name: sync.pods.enabled
        value: 'true'
      - name: sync.events.enabled
        value: 'true'
      - name: sync.persistentvolumeclaims.enabled
        value: 'true'
      - name: sync.ingresses.enabled
        value: 'true'
      - name: sync.fake-nodes.enabled
        value: 'true'
      - name: sync.fake-persistentvolumes.enabled
        value: 'true'
      - name: sync.nodes.enabled
        value: 'false'
      - name: sync.nodes.syncAllNodes
        value: 'false'
      - name: sync.nodes.nodeSelector
        value: ''
      - name: sync.nodes.syncNodeChanges
        value: 'false'
      - name: sync.persistentvolumes.enabled
        value: 'true'
      - name: sync.storageclasses.enabled
        value: 'false'
      - name: sync.priorityclasses.enabled
        value: 'false'
      - name: sync.networkpolicies.enabled
        value: 'false'
      - name: sync.volumesnapshots.enabled
        value: 'false'
      - name: sync.poddisruptionbudgets.enabled
        value: 'false'

      - name: enableHA
        value: 'true'
      - name: syncer.replicas
        value: '3'
      - name: etcd.image
        value: 'k8s.gcr.io/etcd:3.4.13-0'
      - name: etcd.replicas
        value: '3'
      - name: controller.image
        value: 'k8s.gcr.io/kube-controller-manager:v1.21.5'
      - name: controller.replicas
        value: '3'
      - name: api.image
        value: 'k8s.gcr.io/kube-apiserver:v1.21.5'
      - name: api.replicas
        value: '3'
    repoURL: https://charts.loft.sh/
    targetRevision: 0.6.0
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
