apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-k3s-122
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: k3s
    server: https://kubernetes.default.svc
  project: vcluster
  source:
    chart: vcluster
    helm:
      releaseName: vcluster-k3s-122
      parameters:
      - name: service.type
        value: ClusterIP
      - name: vcluster.image
        value: 'rancher/k3s:v1.22.6-k3s1'
      - name: syncer.extraArgs
        value: '{--tls-san=vcluster-k3s-122.172.23.0.3.nip.io,vcluster-k3s-122.k3s.svc.cluster.local}'
      - name: syncer.replicas
        value: '1'
      - name: sync.services.enabled
        value: 'true'
      - name: sync.configmaps.enabled
        value: 'true'
      - name: sync.secrets.enabled
        value: 'true'
      - name: sync.endpoints.enabled
        value: 'true'
      - name: sync.pods.enabled
        value: 'true'
      - name: sync.events.enabled
        value: 'true'
      - name: sync.persistentvolumeclaims.enabled
        value: 'true'
      - name: sync.ingresses.enabled
        value: 'true'
      - name: sync.fake-nodes.enabled
        value: 'true'
      - name: sync.fake-persistentvolumes.enabled
        value: 'true'
      - name: sync.nodes.enabled
        value: 'false'
      - name: sync.nodes.syncAllNodes
        value: 'false'
      - name: sync.nodes.nodeSelector
        value: ''
      - name: sync.nodes.syncNodeChanges
        value: 'false'
      - name: sync.persistentvolumes.enabled
        value: 'true'
      - name: sync.storageclasses.enabled
        value: 'false'
      - name: sync.priorityclasses.enabled
        value: 'false'
      - name: sync.networkpolicies.enabled
        value: 'false'
      - name: sync.volumesnapshots.enabled
        value: 'false'
      - name: sync.poddisruptionbudgets.enabled
        value: 'false'
    repoURL: https://charts.loft.sh/
    targetRevision: 0.6.0
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
