apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
spec:
  destination:
    namespace: istio-ingress
    server: https://kubernetes.default.svc
  project: vcluster-gitops
  source:
    helm:
      parameters:
      - name: global.hub
        value: docker.io/istio
      - name: global.tag
        value: 1.12.0
    path: manifests/charts/gateways/istio-ingress
    repoURL: https://github.com/istio/istio.git
    targetRevision: 1.12.1
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true