apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: vcluster-gitops
  source:
    path: manifests/charts/istio-control/istio-discovery
    repoURL: https://github.com/istio/istio.git
    targetRevision: 1.12.1
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true