apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-control
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: vcluster-gitops
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.12.4
    helm:
      releaseName: istiod
      values: |-
        global:
          hub: gcr.io/istio-release
          tag: 1.12.4
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true