apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster
  namespace: argocd

spec:
  destination:
    namespace: team-b
    server: https://kubernetes.default.svc
  project: vcluster-gitops
  source:
    chart: vcluster
    helm:
      releaseName: vcluster
      parameters:
      - name: serviceCIDR
        value: 10.43.0.1/12
      - name: service.type
        value: ClusterIP
      - name: syncer.extraArgs
        value: '{--tls-san=vcluster.team-a.192.168.32.3.nip.io}'
    repoURL: https://charts.loft.sh/
    targetRevision: 0.6.0
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=tru