apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-b
  namespace: argocd
spec:
  destination:
    namespace: team-c
    server: https://kubernetes.default.svc
  project: vcluster-gitops
  source:
    chart: vcluster
    helm:
      releaseName: vcluster-b
      parameters:
      - name: service.type
        value: ClusterIP
      - name: syncer.extraArgs
        value: '{--tls-san=vcluster-b.team-c.172.18.0.3.nip.io}'
      values: |-
        sync:
          nodes:
            enabled: true
            syncAllNodes: true
            syncNodeChanges: true
        vcluster:
          image: rancher/k3s:v1.21.9-k3s1
    repoURL: https://charts.loft.sh/
    targetRevision: 0.6.0
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
    - CreateNamespace=true