apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-c
  namespace: argocd
spec:
  destination:
    namespace: team-c
    server: https://kubernetes.default.svc
  project: vcluster-gitops
  source:
    chart: vcluster
    helm:
      releaseName: vcluster-c
      parameters:
      - name: service.type
        value: ClusterIP
      - name: syncer.extraArgs
        value: '{--tls-san=vcluster-c.team-c.172.18.0.3.nip.io}'
      - name: vcluster.image
        value: 'rancher/k3s:v1.21.2-k3s1'
      - name: sync.nodes.syncAllNodes
        value: 'false'
      - name: sync.nodes.enabled
        value: 'false' 
      - name: sync.nodes.nodeSelector
        value: 'node-role.kubernetes.io/master=true'   
      - name: sync.nodes.syncNodeChanges
        value: 'true'
    repoURL: https://charts.loft.sh/
    targetRevision: 0.6.0
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
    - CreateNamespace=true