apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2022-02-25T15:48:08Z"
  generation: 14
  name: vcluster
  namespace: argocd
spec:
  destination:
    namespace: vcluster
    server: https://kubernetes.default.svc
  project: vcluster-gitops
  source:
    chart: vcluster
    helm:
      parameters:
      - name: serviceCIDR
        value: 10.43.0.1/12
      - name: service.type
        value: ClusterIP
      - name: syncer.extraArgs
        value: '{--tls-san=192.168.32.2.vcluster.nip.io}'
    repoURL: https://charts.loft.sh/
    targetRevision: 0.6.0
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true