apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: vcluster-gitops
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.7.1
    helm:
      releaseName: cert-manager
      values: |-
        installCRDs: true
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true