apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: vcluster-gitops
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets/
    targetRevision: 2.1.3
    helm:
      releaseName: sealed-secrets-controller
  syncPolicy:
    automated:
      selfHeal: true