---
kind: Simple
apiVersion: k3d.io/v1alpha4
metadata:
  name: medium
servers: 1
agents: 3
image: docker.io/rancher/k3s:v1.22.6-k3s1
subnet: "172.21.0.0/16"
ports:
- port: 443:443
  nodeFilters:
  - loadbalancer
- port: 80:80
  nodeFilters:
  - loadbalancer
- port: 8080:8080
  nodeFilters:
  - loadbalancer
- port: 8443:8443
  nodeFilters:
  - loadbalancer
options:
  k3d:
    wait: true
    timeout: 1m0s
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
    loadbalancer:
      configOverrides:
      - settings.workerConnections=2048
  k3s:
    extraArgs:
    - arg: --no-deploy=traefik
      nodeFilters:
      - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
