---
kind: Simple
apiVersion: k3d.io/v1alpha4
metadata:
  name: prod
servers: 1
agents: 2
image: docker.io/rancher/k3s:v1.22.6-k3s1
subnet: "172.25.0.0/16"
ports:
# For vCluster
- port: 4444:443
  nodeFilters:
  - loadbalancer
# For ArgoCD
- port: 8090:8080
  nodeFilters:
  - loadbalancer
- port: 8444:8443
  nodeFilters:
  - loadbalancer
options:
  k3d:
    wait: true
    timeout: 1m0s
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
    loadbalancer:
      configOverrides:
      - settings.workerConnections=2048
  k3s:
    extraArgs:
    - arg: --no-deploy=traefik
      nodeFilters:
      - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
