apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-deployment-1-scl
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: apps
    server: https://vcluster-k3s-123.k3s.svc.cluster.local
  project: vcluster-gitops
  source:
    path: simple-nginx-deployment
    repoURL: https://github.com/devopsapp84/sample-apps.git
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
