---
apiVersion: v1
data:
  pass: aW5pdDEyMzQ=
  user: YWRtaW4=
kind: Secret
metadata:
  name: test-sec
---
apiVersion: v1
kind: Pod
metadata:
  name: consume-secret
spec:
  containers:
  - name: secret
    image: nginx
    volumeMounts:
    - name: secret
      mountPath: "/tmp/secret"
      readOnly: true
  volumes:
  - name: secret
    secret:
      secretName: test-sec
