apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-b
  name: test-b
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-b
  template:
    metadata:
      labels:
        app: test-b
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-b
  name: test-b
  namespace: apps
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-b
  type: ClusterIP
