name: Vcluster K3d Sample

on:
  workflow_dispatch:
  push:
    branches:
      - v-actions
    paths:
      - .github/workflows/vcluster-k3d-example.yaml

env:
  ORG: procter-gamble 
  REPO: vcluster-demo
  
jobs:
  k3d-cluster:
    runs-on: [ ubuntu-20.04 ]
    needs: helm-release
    steps:
      - name: Checkout repository
        id: 'checkout'
        uses: actions/checkout@v3

      - name: Create cluster
        uses: AbsaOSS/k3d-action@v2
        continue-on-error: true
        with:
          cluster-name: "gh-$GITHUB_REF_NAME"
          args: >-
              --config=images/scripts/config/gh-a-dev-cluster.conf
      - name: Install kubectl locally
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.22.6'
        id: install

      - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: list nodes
        run: |
            kubectl get nodes
      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Add helm repository
        run: |
            helm repo add pg https://raw.githubusercontent.com/procter-gamble/backstage-image-builder/gh-pages/backstage --username=${{ github.actor }} --password ${{ secrets.GH_HELM_TOKEN }}
            helm repo update 
            helm search repo -l pg
            helm install backstage pg/backstage-base -n backstage-base --create-namespace --set auth.githubToken=${{ secrets.GH_HELM_TOKEN }} --set lighthouse.enabled=false
            helm install backstage pg/backstage-dev -n backstage-dev --create-namespace --set auth.githubToken=${{ secrets.GH_HELM_TOKEN }} --set lighthouse.enabled=false
            helm list -A